// LinkIM Comet 接入层 gRPC 契约（Job/Logic → Comet 下行投递）。
// 命名说明：KickConnReq/KickConnResp 而非 KickReq/Empty，
// 因客户端协议 protocol.proto 已定义 KickReq、logic.proto 已定义 Empty，
// 两者生成到同一 Go 包 pkg/pb 不能重名。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: comet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushFramesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Frames        [][]byte               `protobuf:"bytes,3,rep,name=frames,proto3" json:"frames,omitempty"` // 已编码完整的 LinkIM 帧
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushFramesReq) Reset() {
	*x = PushFramesReq{}
	mi := &file_comet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushFramesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFramesReq) ProtoMessage() {}

func (x *PushFramesReq) ProtoReflect() protoreflect.Message {
	mi := &file_comet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFramesReq.ProtoReflect.Descriptor instead.
func (*PushFramesReq) Descriptor() ([]byte, []int) {
	return file_comet_proto_rawDescGZIP(), []int{0}
}

func (x *PushFramesReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PushFramesReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PushFramesReq) GetFrames() [][]byte {
	if x != nil {
		return x.Frames
	}
	return nil
}

type PushFramesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Online        bool                   `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"` // 目标连接是否在本机在线
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushFramesResp) Reset() {
	*x = PushFramesResp{}
	mi := &file_comet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushFramesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFramesResp) ProtoMessage() {}

func (x *PushFramesResp) ProtoReflect() protoreflect.Message {
	mi := &file_comet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFramesResp.ProtoReflect.Descriptor instead.
func (*PushFramesResp) Descriptor() ([]byte, []int) {
	return file_comet_proto_rawDescGZIP(), []int{1}
}

func (x *PushFramesResp) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type KickConnReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickConnReq) Reset() {
	*x = KickConnReq{}
	mi := &file_comet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickConnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickConnReq) ProtoMessage() {}

func (x *KickConnReq) ProtoReflect() protoreflect.Message {
	mi := &file_comet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickConnReq.ProtoReflect.Descriptor instead.
func (*KickConnReq) Descriptor() ([]byte, []int) {
	return file_comet_proto_rawDescGZIP(), []int{2}
}

func (x *KickConnReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *KickConnReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *KickConnReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type KickConnResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickConnResp) Reset() {
	*x = KickConnResp{}
	mi := &file_comet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickConnResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickConnResp) ProtoMessage() {}

func (x *KickConnResp) ProtoReflect() protoreflect.Message {
	mi := &file_comet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickConnResp.ProtoReflect.Descriptor instead.
func (*KickConnResp) Descriptor() ([]byte, []int) {
	return file_comet_proto_rawDescGZIP(), []int{3}
}

var File_comet_proto protoreflect.FileDescriptor

const file_comet_proto_rawDesc = "" +
	"\n" +
	"\vcomet.proto\x12\x0flinkim.comet.v1\"V\n" +
	"\rPushFramesReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06frames\x18\x03 \x03(\fR\x06frames\"(\n" +
	"\x0ePushFramesResp\x12\x16\n" +
	"\x06online\x18\x01 \x01(\bR\x06online\"T\n" +
	"\vKickConnReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x0e\n" +
	"\fKickConnResp2\x9b\x01\n" +
	"\x05Comet\x12M\n" +
	"\n" +
	"PushFrames\x12\x1e.linkim.comet.v1.PushFramesReq\x1a\x1f.linkim.comet.v1.PushFramesResp\x12C\n" +
	"\x04Kick\x12\x1c.linkim.comet.v1.KickConnReq\x1a\x1d.linkim.comet.v1.KickConnRespB!Z\x1fgithub.com/linkim/linkim/pkg/pbb\x06proto3"

var (
	file_comet_proto_rawDescOnce sync.Once
	file_comet_proto_rawDescData []byte
)

func file_comet_proto_rawDescGZIP() []byte {
	file_comet_proto_rawDescOnce.Do(func() {
		file_comet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comet_proto_rawDesc), len(file_comet_proto_rawDesc)))
	})
	return file_comet_proto_rawDescData
}

var file_comet_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_comet_proto_goTypes = []any{
	(*PushFramesReq)(nil),  // 0: linkim.comet.v1.PushFramesReq
	(*PushFramesResp)(nil), // 1: linkim.comet.v1.PushFramesResp
	(*KickConnReq)(nil),    // 2: linkim.comet.v1.KickConnReq
	(*KickConnResp)(nil),   // 3: linkim.comet.v1.KickConnResp
}
var file_comet_proto_depIdxs = []int32{
	0, // 0: linkim.comet.v1.Comet.PushFrames:input_type -> linkim.comet.v1.PushFramesReq
	2, // 1: linkim.comet.v1.Comet.Kick:input_type -> linkim.comet.v1.KickConnReq
	1, // 2: linkim.comet.v1.Comet.PushFrames:output_type -> linkim.comet.v1.PushFramesResp
	3, // 3: linkim.comet.v1.Comet.Kick:output_type -> linkim.comet.v1.KickConnResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_comet_proto_init() }
func file_comet_proto_init() {
	if File_comet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comet_proto_rawDesc), len(file_comet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comet_proto_goTypes,
		DependencyIndexes: file_comet_proto_depIdxs,
		MessageInfos:      file_comet_proto_msgTypes,
	}.Build()
	File_comet_proto = out.File
	file_comet_proto_goTypes = nil
	file_comet_proto_depIdxs = nil
}
