// LinkIM Comet 接入层 gRPC 契约（Job/Logic → Comet 下行投递）。
// 命名说明：KickConnReq/KickConnResp 而非 KickReq/Empty，
// 因客户端协议 protocol.proto 已定义 KickReq、logic.proto 已定义 Empty，
// 两者生成到同一 Go 包 pkg/pb 不能重名。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: comet.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Comet_PushFrames_FullMethodName = "/linkim.comet.v1.Comet/PushFrames"
	Comet_Kick_FullMethodName       = "/linkim.comet.v1.Comet/Kick"
)

// CometClient is the client API for Comet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CometClient interface {
	// Job 下行批量推帧：按 (uid, device_id) 定位连接写入 send 通道。
	PushFrames(ctx context.Context, in *PushFramesReq, opts ...grpc.CallOption) (*PushFramesResp, error)
	// 踢下线（同端互踢 / 管理操作）：向连接写 Kick 帧后断开。
	Kick(ctx context.Context, in *KickConnReq, opts ...grpc.CallOption) (*KickConnResp, error)
}

type cometClient struct {
	cc grpc.ClientConnInterface
}

func NewCometClient(cc grpc.ClientConnInterface) CometClient {
	return &cometClient{cc}
}

func (c *cometClient) PushFrames(ctx context.Context, in *PushFramesReq, opts ...grpc.CallOption) (*PushFramesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushFramesResp)
	err := c.cc.Invoke(ctx, Comet_PushFrames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) Kick(ctx context.Context, in *KickConnReq, opts ...grpc.CallOption) (*KickConnResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KickConnResp)
	err := c.cc.Invoke(ctx, Comet_Kick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CometServer is the server API for Comet service.
// All implementations must embed UnimplementedCometServer
// for forward compatibility.
type CometServer interface {
	// Job 下行批量推帧：按 (uid, device_id) 定位连接写入 send 通道。
	PushFrames(context.Context, *PushFramesReq) (*PushFramesResp, error)
	// 踢下线（同端互踢 / 管理操作）：向连接写 Kick 帧后断开。
	Kick(context.Context, *KickConnReq) (*KickConnResp, error)
	mustEmbedUnimplementedCometServer()
}

// UnimplementedCometServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCometServer struct{}

func (UnimplementedCometServer) PushFrames(context.Context, *PushFramesReq) (*PushFramesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PushFrames not implemented")
}
func (UnimplementedCometServer) Kick(context.Context, *KickConnReq) (*KickConnResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Kick not implemented")
}
func (UnimplementedCometServer) mustEmbedUnimplementedCometServer() {}
func (UnimplementedCometServer) testEmbeddedByValue()               {}

// UnsafeCometServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CometServer will
// result in compilation errors.
type UnsafeCometServer interface {
	mustEmbedUnimplementedCometServer()
}

func RegisterCometServer(s grpc.ServiceRegistrar, srv CometServer) {
	// If the following call panics, it indicates UnimplementedCometServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Comet_ServiceDesc, srv)
}

func _Comet_PushFrames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushFramesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).PushFrames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comet_PushFrames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).PushFrames(ctx, req.(*PushFramesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_Kick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickConnReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).Kick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comet_Kick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).Kick(ctx, req.(*KickConnReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Comet_ServiceDesc is the grpc.ServiceDesc for Comet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Comet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "linkim.comet.v1.Comet",
	HandlerType: (*CometServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushFrames",
			Handler:    _Comet_PushFrames_Handler,
		},
		{
			MethodName: "Kick",
			Handler:    _Comet_Kick_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comet.proto",
}
