// LinkIM Logic 服务 gRPC 契约（设计文档 2.2、5.2）。
// Comet 与 Job 通过本接口调用逻辑层；S4 仅实现 VerifyToken，其余占位。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: logic.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Logic_VerifyToken_FullMethodName     = "/linkim.logic.v1.Logic/VerifyToken"
	Logic_SendMsg_FullMethodName         = "/linkim.logic.v1.Logic/SendMsg"
	Logic_SyncPull_FullMethodName        = "/linkim.logic.v1.Logic/SyncPull"
	Logic_ReportDelivered_FullMethodName = "/linkim.logic.v1.Logic/ReportDelivered"
	Logic_OnlineEvent_FullMethodName     = "/linkim.logic.v1.Logic/OnlineEvent"
	Logic_GetPendingConvs_FullMethodName = "/linkim.logic.v1.Logic/GetPendingConvs"
	Logic_MarkRead_FullMethodName        = "/linkim.logic.v1.Logic/MarkRead"
)

// LogicClient is the client API for Logic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogicClient interface {
	// Comet AUTH 时调用：校验 token（Redis 缓存 5min，miss 回源 account）。
	VerifyToken(ctx context.Context, in *VerifyTokenReq, opts ...grpc.CallOption) (*VerifyTokenResp, error)
	// S6 实现：单聊/群聊上行消息处理（幂等/seq/msgId/写 Kafka）。
	SendMsg(ctx context.Context, in *SendMsgReq, opts ...grpc.CallOption) (*SendMsgAck, error)
	// S8 实现：按会话 seq 增量拉取离线消息。
	// 复用客户端协议的 linkim.pb.v1.SyncPullReq（含 comet 回填的 uid 字段），
	// 避免与 pkg/pb 中同名消息冲突；comet 解帧后可直接透传。
	SyncPull(ctx context.Context, in *SyncPullReq, opts ...grpc.CallOption) (*SyncPullResp, error)
	// S7 实现：接收端已投递回执（观测用）。
	ReportDelivered(ctx context.Context, in *ReportDeliveredReq, opts ...grpc.CallOption) (*Empty, error)
	// S8 实现：上下线事件。上线时返回该用户有未读增量的会话列表
	// （复用 ConvBrief，comet 组装 SYNC_NOTIFY 帧推给刚上线的连接）。
	OnlineEvent(ctx context.Context, in *OnlineEventReq, opts ...grpc.CallOption) (*PendingResp, error)
	// S8 实现：查询 uid 的未读会话列表（last_seq > read_seq）。
	GetPendingConvs(ctx context.Context, in *PendingReq, opts ...grpc.CallOption) (*PendingResp, error)
	// S8 实现：已读上报，推进 read_seq 游标并扣减未读。
	MarkRead(ctx context.Context, in *MarkReadReq, opts ...grpc.CallOption) (*Empty, error)
}

type logicClient struct {
	cc grpc.ClientConnInterface
}

func NewLogicClient(cc grpc.ClientConnInterface) LogicClient {
	return &logicClient{cc}
}

func (c *logicClient) VerifyToken(ctx context.Context, in *VerifyTokenReq, opts ...grpc.CallOption) (*VerifyTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyTokenResp)
	err := c.cc.Invoke(ctx, Logic_VerifyToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicClient) SendMsg(ctx context.Context, in *SendMsgReq, opts ...grpc.CallOption) (*SendMsgAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMsgAck)
	err := c.cc.Invoke(ctx, Logic_SendMsg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicClient) SyncPull(ctx context.Context, in *SyncPullReq, opts ...grpc.CallOption) (*SyncPullResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncPullResp)
	err := c.cc.Invoke(ctx, Logic_SyncPull_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicClient) ReportDelivered(ctx context.Context, in *ReportDeliveredReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Logic_ReportDelivered_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicClient) OnlineEvent(ctx context.Context, in *OnlineEventReq, opts ...grpc.CallOption) (*PendingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PendingResp)
	err := c.cc.Invoke(ctx, Logic_OnlineEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicClient) GetPendingConvs(ctx context.Context, in *PendingReq, opts ...grpc.CallOption) (*PendingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PendingResp)
	err := c.cc.Invoke(ctx, Logic_GetPendingConvs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicClient) MarkRead(ctx context.Context, in *MarkReadReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Logic_MarkRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogicServer is the server API for Logic service.
// All implementations must embed UnimplementedLogicServer
// for forward compatibility.
type LogicServer interface {
	// Comet AUTH 时调用：校验 token（Redis 缓存 5min，miss 回源 account）。
	VerifyToken(context.Context, *VerifyTokenReq) (*VerifyTokenResp, error)
	// S6 实现：单聊/群聊上行消息处理（幂等/seq/msgId/写 Kafka）。
	SendMsg(context.Context, *SendMsgReq) (*SendMsgAck, error)
	// S8 实现：按会话 seq 增量拉取离线消息。
	// 复用客户端协议的 linkim.pb.v1.SyncPullReq（含 comet 回填的 uid 字段），
	// 避免与 pkg/pb 中同名消息冲突；comet 解帧后可直接透传。
	SyncPull(context.Context, *SyncPullReq) (*SyncPullResp, error)
	// S7 实现：接收端已投递回执（观测用）。
	ReportDelivered(context.Context, *ReportDeliveredReq) (*Empty, error)
	// S8 实现：上下线事件。上线时返回该用户有未读增量的会话列表
	// （复用 ConvBrief，comet 组装 SYNC_NOTIFY 帧推给刚上线的连接）。
	OnlineEvent(context.Context, *OnlineEventReq) (*PendingResp, error)
	// S8 实现：查询 uid 的未读会话列表（last_seq > read_seq）。
	GetPendingConvs(context.Context, *PendingReq) (*PendingResp, error)
	// S8 实现：已读上报，推进 read_seq 游标并扣减未读。
	MarkRead(context.Context, *MarkReadReq) (*Empty, error)
	mustEmbedUnimplementedLogicServer()
}

// UnimplementedLogicServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogicServer struct{}

func (UnimplementedLogicServer) VerifyToken(context.Context, *VerifyTokenReq) (*VerifyTokenResp, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyToken not implemented")
}
func (UnimplementedLogicServer) SendMsg(context.Context, *SendMsgReq) (*SendMsgAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMsg not implemented")
}
func (UnimplementedLogicServer) SyncPull(context.Context, *SyncPullReq) (*SyncPullResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncPull not implemented")
}
func (UnimplementedLogicServer) ReportDelivered(context.Context, *ReportDeliveredReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportDelivered not implemented")
}
func (UnimplementedLogicServer) OnlineEvent(context.Context, *OnlineEventReq) (*PendingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method OnlineEvent not implemented")
}
func (UnimplementedLogicServer) GetPendingConvs(context.Context, *PendingReq) (*PendingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingConvs not implemented")
}
func (UnimplementedLogicServer) MarkRead(context.Context, *MarkReadReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkRead not implemented")
}
func (UnimplementedLogicServer) mustEmbedUnimplementedLogicServer() {}
func (UnimplementedLogicServer) testEmbeddedByValue()               {}

// UnsafeLogicServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogicServer will
// result in compilation errors.
type UnsafeLogicServer interface {
	mustEmbedUnimplementedLogicServer()
}

func RegisterLogicServer(s grpc.ServiceRegistrar, srv LogicServer) {
	// If the following call panics, it indicates UnimplementedLogicServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Logic_ServiceDesc, srv)
}

func _Logic_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Logic_VerifyToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServer).VerifyToken(ctx, req.(*VerifyTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logic_SendMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServer).SendMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Logic_SendMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServer).SendMsg(ctx, req.(*SendMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logic_SyncPull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncPullReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServer).SyncPull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Logic_SyncPull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServer).SyncPull(ctx, req.(*SyncPullReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logic_ReportDelivered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportDeliveredReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServer).ReportDelivered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Logic_ReportDelivered_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServer).ReportDelivered(ctx, req.(*ReportDeliveredReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logic_OnlineEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlineEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServer).OnlineEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Logic_OnlineEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServer).OnlineEvent(ctx, req.(*OnlineEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logic_GetPendingConvs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PendingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServer).GetPendingConvs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Logic_GetPendingConvs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServer).GetPendingConvs(ctx, req.(*PendingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logic_MarkRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServer).MarkRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Logic_MarkRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServer).MarkRead(ctx, req.(*MarkReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Logic_ServiceDesc is the grpc.ServiceDesc for Logic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Logic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "linkim.logic.v1.Logic",
	HandlerType: (*LogicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyToken",
			Handler:    _Logic_VerifyToken_Handler,
		},
		{
			MethodName: "SendMsg",
			Handler:    _Logic_SendMsg_Handler,
		},
		{
			MethodName: "SyncPull",
			Handler:    _Logic_SyncPull_Handler,
		},
		{
			MethodName: "ReportDelivered",
			Handler:    _Logic_ReportDelivered_Handler,
		},
		{
			MethodName: "OnlineEvent",
			Handler:    _Logic_OnlineEvent_Handler,
		},
		{
			MethodName: "GetPendingConvs",
			Handler:    _Logic_GetPendingConvs_Handler,
		},
		{
			MethodName: "MarkRead",
			Handler:    _Logic_MarkRead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logic.proto",
}
