// LinkIM Logic 服务 gRPC 契约（设计文档 2.2、5.2）。
// Comet 与 Job 通过本接口调用逻辑层；S4 仅实现 VerifyToken，其余占位。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: logic.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenReq) Reset() {
	*x = VerifyTokenReq{}
	mi := &file_logic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenReq) ProtoMessage() {}

func (x *VerifyTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenReq.ProtoReflect.Descriptor instead.
func (*VerifyTokenReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyTokenReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *VerifyTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"` // 0 有效；40101 无效；50102 account 不可达
	Uid           int64                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`   // token 归属的真实 uid（account 返回），comet 据此绑定连接
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResp) Reset() {
	*x = VerifyTokenResp{}
	mi := &file_logic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResp) ProtoMessage() {}

func (x *VerifyTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResp.ProtoReflect.Descriptor instead.
func (*VerifyTokenResp) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyTokenResp) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyTokenResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *VerifyTokenResp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type SendMsgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int64                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ConvId        string                 `protobuf:"bytes,2,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	ConvType      int32                  `protobuf:"varint,3,opt,name=conv_type,json=convType,proto3" json:"conv_type,omitempty"`           // 1单聊 2群聊
	ClientMsgId   string                 `protobuf:"bytes,4,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"` // 幂等键
	DeviceId      string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	MsgType       int32                  `protobuf:"varint,6,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMsgReq) Reset() {
	*x = SendMsgReq{}
	mi := &file_logic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgReq) ProtoMessage() {}

func (x *SendMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgReq.ProtoReflect.Descriptor instead.
func (*SendMsgReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{2}
}

func (x *SendMsgReq) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendMsgReq) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

func (x *SendMsgReq) GetConvType() int32 {
	if x != nil {
		return x.ConvType
	}
	return 0
}

func (x *SendMsgReq) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *SendMsgReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SendMsgReq) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *SendMsgReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendMsgAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	MsgId         string                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMsgAck) Reset() {
	*x = SendMsgAck{}
	mi := &file_logic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMsgAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgAck) ProtoMessage() {}

func (x *SendMsgAck) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgAck.ProtoReflect.Descriptor instead.
func (*SendMsgAck) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{3}
}

func (x *SendMsgAck) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendMsgAck) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *SendMsgAck) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SendMsgAck) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SyncPullResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Messages      []*PbMsg               `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	MaxSeq        int64                  `protobuf:"varint,3,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPullResp) Reset() {
	*x = SyncPullResp{}
	mi := &file_logic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPullResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPullResp) ProtoMessage() {}

func (x *SyncPullResp) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPullResp.ProtoReflect.Descriptor instead.
func (*SyncPullResp) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{4}
}

func (x *SyncPullResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SyncPullResp) GetMessages() []*PbMsg {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SyncPullResp) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

// PbMsg 是跨服务传递的消息统一结构（Kafka msg.push/msg.store 的 value）。
type PbMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ConvId        string                 `protobuf:"bytes,2,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	ConvType      int32                  `protobuf:"varint,3,opt,name=conv_type,json=convType,proto3" json:"conv_type,omitempty"`
	SenderId      int64                  `protobuf:"varint,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	MsgType       int32                  `protobuf:"varint,5,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Seq           int64                  `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty"`
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"` // 0正常 1已撤回
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbMsg) Reset() {
	*x = PbMsg{}
	mi := &file_logic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbMsg) ProtoMessage() {}

func (x *PbMsg) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbMsg.ProtoReflect.Descriptor instead.
func (*PbMsg) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{5}
}

func (x *PbMsg) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *PbMsg) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

func (x *PbMsg) GetConvType() int32 {
	if x != nil {
		return x.ConvType
	}
	return 0
}

func (x *PbMsg) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *PbMsg) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *PbMsg) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PbMsg) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PbMsg) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PbMsg) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ReportDeliveredReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	MsgId         string                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ConvId        string                 `protobuf:"bytes,3,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDeliveredReq) Reset() {
	*x = ReportDeliveredReq{}
	mi := &file_logic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDeliveredReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDeliveredReq) ProtoMessage() {}

func (x *ReportDeliveredReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDeliveredReq.ProtoReflect.Descriptor instead.
func (*ReportDeliveredReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{6}
}

func (x *ReportDeliveredReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReportDeliveredReq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *ReportDeliveredReq) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

type OnlineEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Platform      int32                  `protobuf:"varint,3,opt,name=platform,proto3" json:"platform,omitempty"`
	CometAddr     string                 `protobuf:"bytes,4,opt,name=comet_addr,json=cometAddr,proto3" json:"comet_addr,omitempty"`
	Online        bool                   `protobuf:"varint,5,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineEventReq) Reset() {
	*x = OnlineEventReq{}
	mi := &file_logic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineEventReq) ProtoMessage() {}

func (x *OnlineEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineEventReq.ProtoReflect.Descriptor instead.
func (*OnlineEventReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{7}
}

func (x *OnlineEventReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *OnlineEventReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *OnlineEventReq) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *OnlineEventReq) GetCometAddr() string {
	if x != nil {
		return x.CometAddr
	}
	return ""
}

func (x *OnlineEventReq) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_logic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{8}
}

type PendingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingReq) Reset() {
	*x = PendingReq{}
	mi := &file_logic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingReq) ProtoMessage() {}

func (x *PendingReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingReq.ProtoReflect.Descriptor instead.
func (*PendingReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{9}
}

func (x *PendingReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type PendingResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 复用客户端协议的 ConvBrief，避免与 pkg/pb 中同名消息冲突。
	Convs         []*ConvBrief `protobuf:"bytes,1,rep,name=convs,proto3" json:"convs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingResp) Reset() {
	*x = PendingResp{}
	mi := &file_logic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingResp) ProtoMessage() {}

func (x *PendingResp) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingResp.ProtoReflect.Descriptor instead.
func (*PendingResp) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{10}
}

func (x *PendingResp) GetConvs() []*ConvBrief {
	if x != nil {
		return x.Convs
	}
	return nil
}

type MarkReadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ConvId        string                 `protobuf:"bytes,2,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"` // 已读到的会话 seq（新游标）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadReq) Reset() {
	*x = MarkReadReq{}
	mi := &file_logic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadReq) ProtoMessage() {}

func (x *MarkReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadReq.ProtoReflect.Descriptor instead.
func (*MarkReadReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{11}
}

func (x *MarkReadReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MarkReadReq) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

func (x *MarkReadReq) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// Envelope 是 msg.push 的 value：接收者 + 消息本体。
// 单聊与群聊统一使用（群聊由 Logic 按成员逐个副本写入，recv_uid 唯一，
// 保证同一接收者的消息落在同一 Kafka 分区从而有序，设计文档 11.2）。
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecvUid       int64                  `protobuf:"varint,1,opt,name=recv_uid,json=recvUid,proto3" json:"recv_uid,omitempty"`
	Msg           *PbMsg                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_logic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{12}
}

func (x *Envelope) GetRecvUid() int64 {
	if x != nil {
		return x.RecvUid
	}
	return 0
}

func (x *Envelope) GetMsg() *PbMsg {
	if x != nil {
		return x.Msg
	}
	return nil
}

var File_logic_proto protoreflect.FileDescriptor

const file_logic_proto_rawDesc = "" +
	"\n" +
	"\vlogic.proto\x12\x0flinkim.logic.v1\x1a\x0eprotocol.proto\"8\n" +
	"\x0eVerifyTokenReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"M\n" +
	"\x0fVerifyTokenResp\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x03R\x03uid\"\xd5\x01\n" +
	"\n" +
	"SendMsgReq\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x03R\bsenderId\x12\x17\n" +
	"\aconv_id\x18\x02 \x01(\tR\x06convId\x12\x1b\n" +
	"\tconv_type\x18\x03 \x01(\x05R\bconvType\x12\"\n" +
	"\rclient_msg_id\x18\x04 \x01(\tR\vclientMsgId\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\x12\x19\n" +
	"\bmsg_type\x18\x06 \x01(\x05R\amsgType\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\"g\n" +
	"\n" +
	"SendMsgAck\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\tR\x05msgId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"o\n" +
	"\fSyncPullResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x122\n" +
	"\bmessages\x18\x02 \x03(\v2\x16.linkim.logic.v1.PbMsgR\bmessages\x12\x17\n" +
	"\amax_seq\x18\x03 \x01(\x03R\x06maxSeq\"\xee\x01\n" +
	"\x05PbMsg\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x17\n" +
	"\aconv_id\x18\x02 \x01(\tR\x06convId\x12\x1b\n" +
	"\tconv_type\x18\x03 \x01(\x05R\bconvType\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\x03R\bsenderId\x12\x19\n" +
	"\bmsg_type\x18\x05 \x01(\x05R\amsgType\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x10\n" +
	"\x03seq\x18\a \x01(\x03R\x03seq\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\"V\n" +
	"\x12ReportDeliveredReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\tR\x05msgId\x12\x17\n" +
	"\aconv_id\x18\x03 \x01(\tR\x06convId\"\x92\x01\n" +
	"\x0eOnlineEventReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\x05R\bplatform\x12\x1d\n" +
	"\n" +
	"comet_addr\x18\x04 \x01(\tR\tcometAddr\x12\x16\n" +
	"\x06online\x18\x05 \x01(\bR\x06online\"\a\n" +
	"\x05Empty\"\x1e\n" +
	"\n" +
	"PendingReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"<\n" +
	"\vPendingResp\x12-\n" +
	"\x05convs\x18\x01 \x03(\v2\x17.linkim.pb.v1.ConvBriefR\x05convs\"J\n" +
	"\vMarkReadReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x17\n" +
	"\aconv_id\x18\x02 \x01(\tR\x06convId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\"O\n" +
	"\bEnvelope\x12\x19\n" +
	"\brecv_uid\x18\x01 \x01(\x03R\arecvUid\x12(\n" +
	"\x03msg\x18\x02 \x01(\v2\x16.linkim.logic.v1.PbMsgR\x03msg2\x92\x04\n" +
	"\x05Logic\x12P\n" +
	"\vVerifyToken\x12\x1f.linkim.logic.v1.VerifyTokenReq\x1a .linkim.logic.v1.VerifyTokenResp\x12C\n" +
	"\aSendMsg\x12\x1b.linkim.logic.v1.SendMsgReq\x1a\x1b.linkim.logic.v1.SendMsgAck\x12D\n" +
	"\bSyncPull\x12\x19.linkim.pb.v1.SyncPullReq\x1a\x1d.linkim.logic.v1.SyncPullResp\x12N\n" +
	"\x0fReportDelivered\x12#.linkim.logic.v1.ReportDeliveredReq\x1a\x16.linkim.logic.v1.Empty\x12L\n" +
	"\vOnlineEvent\x12\x1f.linkim.logic.v1.OnlineEventReq\x1a\x1c.linkim.logic.v1.PendingResp\x12L\n" +
	"\x0fGetPendingConvs\x12\x1b.linkim.logic.v1.PendingReq\x1a\x1c.linkim.logic.v1.PendingResp\x12@\n" +
	"\bMarkRead\x12\x1c.linkim.logic.v1.MarkReadReq\x1a\x16.linkim.logic.v1.EmptyB!Z\x1fgithub.com/linkim/linkim/pkg/pbb\x06proto3"

var (
	file_logic_proto_rawDescOnce sync.Once
	file_logic_proto_rawDescData []byte
)

func file_logic_proto_rawDescGZIP() []byte {
	file_logic_proto_rawDescOnce.Do(func() {
		file_logic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logic_proto_rawDesc), len(file_logic_proto_rawDesc)))
	})
	return file_logic_proto_rawDescData
}

var file_logic_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_logic_proto_goTypes = []any{
	(*VerifyTokenReq)(nil),     // 0: linkim.logic.v1.VerifyTokenReq
	(*VerifyTokenResp)(nil),    // 1: linkim.logic.v1.VerifyTokenResp
	(*SendMsgReq)(nil),         // 2: linkim.logic.v1.SendMsgReq
	(*SendMsgAck)(nil),         // 3: linkim.logic.v1.SendMsgAck
	(*SyncPullResp)(nil),       // 4: linkim.logic.v1.SyncPullResp
	(*PbMsg)(nil),              // 5: linkim.logic.v1.PbMsg
	(*ReportDeliveredReq)(nil), // 6: linkim.logic.v1.ReportDeliveredReq
	(*OnlineEventReq)(nil),     // 7: linkim.logic.v1.OnlineEventReq
	(*Empty)(nil),              // 8: linkim.logic.v1.Empty
	(*PendingReq)(nil),         // 9: linkim.logic.v1.PendingReq
	(*PendingResp)(nil),        // 10: linkim.logic.v1.PendingResp
	(*MarkReadReq)(nil),        // 11: linkim.logic.v1.MarkReadReq
	(*Envelope)(nil),           // 12: linkim.logic.v1.Envelope
	(*ConvBrief)(nil),          // 13: linkim.pb.v1.ConvBrief
	(*SyncPullReq)(nil),        // 14: linkim.pb.v1.SyncPullReq
}
var file_logic_proto_depIdxs = []int32{
	5,  // 0: linkim.logic.v1.SyncPullResp.messages:type_name -> linkim.logic.v1.PbMsg
	13, // 1: linkim.logic.v1.PendingResp.convs:type_name -> linkim.pb.v1.ConvBrief
	5,  // 2: linkim.logic.v1.Envelope.msg:type_name -> linkim.logic.v1.PbMsg
	0,  // 3: linkim.logic.v1.Logic.VerifyToken:input_type -> linkim.logic.v1.VerifyTokenReq
	2,  // 4: linkim.logic.v1.Logic.SendMsg:input_type -> linkim.logic.v1.SendMsgReq
	14, // 5: linkim.logic.v1.Logic.SyncPull:input_type -> linkim.pb.v1.SyncPullReq
	6,  // 6: linkim.logic.v1.Logic.ReportDelivered:input_type -> linkim.logic.v1.ReportDeliveredReq
	7,  // 7: linkim.logic.v1.Logic.OnlineEvent:input_type -> linkim.logic.v1.OnlineEventReq
	9,  // 8: linkim.logic.v1.Logic.GetPendingConvs:input_type -> linkim.logic.v1.PendingReq
	11, // 9: linkim.logic.v1.Logic.MarkRead:input_type -> linkim.logic.v1.MarkReadReq
	1,  // 10: linkim.logic.v1.Logic.VerifyToken:output_type -> linkim.logic.v1.VerifyTokenResp
	3,  // 11: linkim.logic.v1.Logic.SendMsg:output_type -> linkim.logic.v1.SendMsgAck
	4,  // 12: linkim.logic.v1.Logic.SyncPull:output_type -> linkim.logic.v1.SyncPullResp
	8,  // 13: linkim.logic.v1.Logic.ReportDelivered:output_type -> linkim.logic.v1.Empty
	10, // 14: linkim.logic.v1.Logic.OnlineEvent:output_type -> linkim.logic.v1.PendingResp
	10, // 15: linkim.logic.v1.Logic.GetPendingConvs:output_type -> linkim.logic.v1.PendingResp
	8,  // 16: linkim.logic.v1.Logic.MarkRead:output_type -> linkim.logic.v1.Empty
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_logic_proto_init() }
func file_logic_proto_init() {
	if File_logic_proto != nil {
		return
	}
	file_protocol_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logic_proto_rawDesc), len(file_logic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logic_proto_goTypes,
		DependencyIndexes: file_logic_proto_depIdxs,
		MessageInfos:      file_logic_proto_msgTypes,
	}.Build()
	File_logic_proto = out.File
	file_logic_proto_goTypes = nil
	file_logic_proto_depIdxs = nil
}
