// LinkIM 客户端-服务端通信协议消息定义（设计文档 4.4）。
// 帧格式见 pkg/protocol；本文件的 message 作为帧 body 的 Protobuf 编码。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: protocol.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MSG_SEND 请求体 (cmd=0x05)
type MsgSendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgId   string                 `protobuf:"bytes,1,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"` // 客户端生成 UUID，用于幂等去重
	ConvId        string                 `protobuf:"bytes,2,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`                  // 会话 ID
	ConvType      int32                  `protobuf:"varint,3,opt,name=conv_type,json=convType,proto3" json:"conv_type,omitempty"`           // 1单聊 2群聊
	MsgType       int32                  `protobuf:"varint,4,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`              // 1文本 2图片 3语音...
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`                              // 消息体
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSendReq) Reset() {
	*x = MsgSendReq{}
	mi := &file_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSendReq) ProtoMessage() {}

func (x *MsgSendReq) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSendReq.ProtoReflect.Descriptor instead.
func (*MsgSendReq) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *MsgSendReq) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *MsgSendReq) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

func (x *MsgSendReq) GetConvType() int32 {
	if x != nil {
		return x.ConvType
	}
	return 0
}

func (x *MsgSendReq) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *MsgSendReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// MSG_SEND_ACK 响应体 (cmd=0x06)
type MsgSendAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	ClientMsgId   string                 `protobuf:"bytes,2,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"` // 回带，客户端据此结束重发定时器
	MsgId         string                 `protobuf:"bytes,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                     // 服务端全局唯一消息 ID（雪花）
	Seq           int64                  `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`                                     // 会话内递增序列号
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSendAck) Reset() {
	*x = MsgSendAck{}
	mi := &file_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSendAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSendAck) ProtoMessage() {}

func (x *MsgSendAck) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSendAck.ProtoReflect.Descriptor instead.
func (*MsgSendAck) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *MsgSendAck) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MsgSendAck) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *MsgSendAck) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *MsgSendAck) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MsgSendAck) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// MSG_PUSH 推送体 (cmd=0x07)
type MsgPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ConvId        string                 `protobuf:"bytes,2,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	ConvType      int32                  `protobuf:"varint,3,opt,name=conv_type,json=convType,proto3" json:"conv_type,omitempty"`
	SenderId      int64                  `protobuf:"varint,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	MsgType       int32                  `protobuf:"varint,5,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Seq           int64                  `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty"` // 接收方据此去重与排序
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgPush) Reset() {
	*x = MsgPush{}
	mi := &file_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPush) ProtoMessage() {}

func (x *MsgPush) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPush.ProtoReflect.Descriptor instead.
func (*MsgPush) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *MsgPush) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *MsgPush) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

func (x *MsgPush) GetConvType() int32 {
	if x != nil {
		return x.ConvType
	}
	return 0
}

func (x *MsgPush) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *MsgPush) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *MsgPush) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MsgPush) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MsgPush) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// MSG_RECEIVED_ACK 请求体 (cmd=0x08)：客户端已接收确认
type ReceivedAckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ConvId        string                 `protobuf:"bytes,2,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceivedAckReq) Reset() {
	*x = ReceivedAckReq{}
	mi := &file_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceivedAckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivedAckReq) ProtoMessage() {}

func (x *ReceivedAckReq) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivedAckReq.ProtoReflect.Descriptor instead.
func (*ReceivedAckReq) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *ReceivedAckReq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *ReceivedAckReq) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

func (x *ReceivedAckReq) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// AUTH 请求体 (cmd=0x01)
type AuthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Platform      int32                  `protobuf:"varint,3,opt,name=platform,proto3" json:"platform,omitempty"` // 1手机 2平板 3桌面 4Web（同端互踢按 platform 判定）
	Uid           int64                  `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`           // 登录接口返回的 uid；服务端校验与 token 一致性后使用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthReq) Reset() {
	*x = AuthReq{}
	mi := &file_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReq) ProtoMessage() {}

func (x *AuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReq.ProtoReflect.Descriptor instead.
func (*AuthReq) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *AuthReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AuthReq) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *AuthReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

// AUTH_ACK 响应体 (cmd=0x02)
type AuthAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Uid           int64                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	KickReason    int32                  `protobuf:"varint,4,opt,name=kick_reason,json=kickReason,proto3" json:"kick_reason,omitempty"` // 被踢下线原因（非 0 表示本连接被同端新登录顶替）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthAck) Reset() {
	*x = AuthAck{}
	mi := &file_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthAck) ProtoMessage() {}

func (x *AuthAck) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthAck.ProtoReflect.Descriptor instead.
func (*AuthAck) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *AuthAck) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AuthAck) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AuthAck) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AuthAck) GetKickReason() int32 {
	if x != nil {
		return x.KickReason
	}
	return 0
}

// HEARTBEAT 请求体 (cmd=0x03)：空消息
type HeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReq) Reset() {
	*x = HeartbeatReq{}
	mi := &file_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReq) ProtoMessage() {}

func (x *HeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReq.ProtoReflect.Descriptor instead.
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{6}
}

// KICK 推送体（服务端主动踢下线前下发）
type KickReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickReq) Reset() {
	*x = KickReq{}
	mi := &file_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickReq) ProtoMessage() {}

func (x *KickReq) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickReq.ProtoReflect.Descriptor instead.
func (*KickReq) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *KickReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// SYNC_PULL 请求体 (cmd=0x09)：携带本地最大 seq 增量拉取
type SyncPullReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        string                 `protobuf:"bytes,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	LocalMaxSeq   int64                  `protobuf:"varint,2,opt,name=local_max_seq,json=localMaxSeq,proto3" json:"local_max_seq,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Uid           int64                  `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"` // 服务端路由用：comet 回填连接归属 uid，客户端不填写
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPullReq) Reset() {
	*x = SyncPullReq{}
	mi := &file_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPullReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPullReq) ProtoMessage() {}

func (x *SyncPullReq) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPullReq.ProtoReflect.Descriptor instead.
func (*SyncPullReq) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *SyncPullReq) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

func (x *SyncPullReq) GetLocalMaxSeq() int64 {
	if x != nil {
		return x.LocalMaxSeq
	}
	return 0
}

func (x *SyncPullReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SyncPullReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

// SYNC_RESP 响应体 (cmd=0x0A)
type SyncResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        string                 `protobuf:"bytes,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Messages      []*MsgPush             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	MaxSeq        int64                  `protobuf:"varint,3,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"` // 会话当前最新 seq，客户端据此判断是否追平
	Code          int32                  `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`                   // 业务码：0 成功；非 0 时 messages 为空
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResp) Reset() {
	*x = SyncResp{}
	mi := &file_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResp) ProtoMessage() {}

func (x *SyncResp) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResp.ProtoReflect.Descriptor instead.
func (*SyncResp) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *SyncResp) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

func (x *SyncResp) GetMessages() []*MsgPush {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SyncResp) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

func (x *SyncResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 会话摘要（SYNC_NOTIFY / pending 列表共用）
type ConvBrief struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        string                 `protobuf:"bytes,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	ConvType      int32                  `protobuf:"varint,2,opt,name=conv_type,json=convType,proto3" json:"conv_type,omitempty"`
	MaxSeq        int64                  `protobuf:"varint,3,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"` // 会话最新 seq
	Unread        int32                  `protobuf:"varint,4,opt,name=unread,proto3" json:"unread,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvBrief) Reset() {
	*x = ConvBrief{}
	mi := &file_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvBrief) ProtoMessage() {}

func (x *ConvBrief) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvBrief.ProtoReflect.Descriptor instead.
func (*ConvBrief) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *ConvBrief) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

func (x *ConvBrief) GetConvType() int32 {
	if x != nil {
		return x.ConvType
	}
	return 0
}

func (x *ConvBrief) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

func (x *ConvBrief) GetUnread() int32 {
	if x != nil {
		return x.Unread
	}
	return 0
}

// SYNC_NOTIFY 推送体（S→C：上线后有未读会话时下发，客户端据此发起 SYNC_PULL）
type SyncNotifyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Convs         []*ConvBrief           `protobuf:"bytes,1,rep,name=convs,proto3" json:"convs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncNotifyReq) Reset() {
	*x = SyncNotifyReq{}
	mi := &file_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncNotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncNotifyReq) ProtoMessage() {}

func (x *SyncNotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncNotifyReq.ProtoReflect.Descriptor instead.
func (*SyncNotifyReq) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *SyncNotifyReq) GetConvs() []*ConvBrief {
	if x != nil {
		return x.Convs
	}
	return nil
}

// RECALL 请求体 (cmd=0x0B)
type MsgRecallReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        string                 `protobuf:"bytes,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	MsgId         string                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRecallReq) Reset() {
	*x = MsgRecallReq{}
	mi := &file_protocol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRecallReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRecallReq) ProtoMessage() {}

func (x *MsgRecallReq) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRecallReq.ProtoReflect.Descriptor instead.
func (*MsgRecallReq) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *MsgRecallReq) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

func (x *MsgRecallReq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

var File_protocol_proto protoreflect.FileDescriptor

const file_protocol_proto_rawDesc = "" +
	"\n" +
	"\x0eprotocol.proto\x12\flinkim.pb.v1\"\x9b\x01\n" +
	"\n" +
	"MsgSendReq\x12\"\n" +
	"\rclient_msg_id\x18\x01 \x01(\tR\vclientMsgId\x12\x17\n" +
	"\aconv_id\x18\x02 \x01(\tR\x06convId\x12\x1b\n" +
	"\tconv_type\x18\x03 \x01(\x05R\bconvType\x12\x19\n" +
	"\bmsg_type\x18\x04 \x01(\x05R\amsgType\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"\x8b\x01\n" +
	"\n" +
	"MsgSendAck\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\"\n" +
	"\rclient_msg_id\x18\x02 \x01(\tR\vclientMsgId\x12\x15\n" +
	"\x06msg_id\x18\x03 \x01(\tR\x05msgId\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x03R\x03seq\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\xd8\x01\n" +
	"\aMsgPush\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x17\n" +
	"\aconv_id\x18\x02 \x01(\tR\x06convId\x12\x1b\n" +
	"\tconv_type\x18\x03 \x01(\x05R\bconvType\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\x03R\bsenderId\x12\x19\n" +
	"\bmsg_type\x18\x05 \x01(\x05R\amsgType\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x10\n" +
	"\x03seq\x18\a \x01(\x03R\x03seq\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"R\n" +
	"\x0eReceivedAckReq\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x17\n" +
	"\aconv_id\x18\x02 \x01(\tR\x06convId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\"j\n" +
	"\aAuthReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\x05R\bplatform\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x03R\x03uid\"b\n" +
	"\aAuthAck\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x03R\x03uid\x12\x1f\n" +
	"\vkick_reason\x18\x04 \x01(\x05R\n" +
	"kickReason\"\x0e\n" +
	"\fHeartbeatReq\"!\n" +
	"\aKickReq\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"r\n" +
	"\vSyncPullReq\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\tR\x06convId\x12\"\n" +
	"\rlocal_max_seq\x18\x02 \x01(\x03R\vlocalMaxSeq\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x03R\x03uid\"\x83\x01\n" +
	"\bSyncResp\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\tR\x06convId\x121\n" +
	"\bmessages\x18\x02 \x03(\v2\x15.linkim.pb.v1.MsgPushR\bmessages\x12\x17\n" +
	"\amax_seq\x18\x03 \x01(\x03R\x06maxSeq\x12\x12\n" +
	"\x04code\x18\x04 \x01(\x05R\x04code\"r\n" +
	"\tConvBrief\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\tR\x06convId\x12\x1b\n" +
	"\tconv_type\x18\x02 \x01(\x05R\bconvType\x12\x17\n" +
	"\amax_seq\x18\x03 \x01(\x03R\x06maxSeq\x12\x16\n" +
	"\x06unread\x18\x04 \x01(\x05R\x06unread\">\n" +
	"\rSyncNotifyReq\x12-\n" +
	"\x05convs\x18\x01 \x03(\v2\x17.linkim.pb.v1.ConvBriefR\x05convs\">\n" +
	"\fMsgRecallReq\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\tR\x06convId\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\tR\x05msgIdB!Z\x1fgithub.com/linkim/linkim/pkg/pbb\x06proto3"

var (
	file_protocol_proto_rawDescOnce sync.Once
	file_protocol_proto_rawDescData []byte
)

func file_protocol_proto_rawDescGZIP() []byte {
	file_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)))
	})
	return file_protocol_proto_rawDescData
}

var file_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_protocol_proto_goTypes = []any{
	(*MsgSendReq)(nil),     // 0: linkim.pb.v1.MsgSendReq
	(*MsgSendAck)(nil),     // 1: linkim.pb.v1.MsgSendAck
	(*MsgPush)(nil),        // 2: linkim.pb.v1.MsgPush
	(*ReceivedAckReq)(nil), // 3: linkim.pb.v1.ReceivedAckReq
	(*AuthReq)(nil),        // 4: linkim.pb.v1.AuthReq
	(*AuthAck)(nil),        // 5: linkim.pb.v1.AuthAck
	(*HeartbeatReq)(nil),   // 6: linkim.pb.v1.HeartbeatReq
	(*KickReq)(nil),        // 7: linkim.pb.v1.KickReq
	(*SyncPullReq)(nil),    // 8: linkim.pb.v1.SyncPullReq
	(*SyncResp)(nil),       // 9: linkim.pb.v1.SyncResp
	(*ConvBrief)(nil),      // 10: linkim.pb.v1.ConvBrief
	(*SyncNotifyReq)(nil),  // 11: linkim.pb.v1.SyncNotifyReq
	(*MsgRecallReq)(nil),   // 12: linkim.pb.v1.MsgRecallReq
}
var file_protocol_proto_depIdxs = []int32{
	2,  // 0: linkim.pb.v1.SyncResp.messages:type_name -> linkim.pb.v1.MsgPush
	10, // 1: linkim.pb.v1.SyncNotifyReq.convs:type_name -> linkim.pb.v1.ConvBrief
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_protocol_proto_init() }
func file_protocol_proto_init() {
	if File_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_proto_depIdxs,
		MessageInfos:      file_protocol_proto_msgTypes,
	}.Build()
	File_protocol_proto = out.File
	file_protocol_proto_goTypes = nil
	file_protocol_proto_depIdxs = nil
}
